# Generated by Django 2.1.3 on 2018-11-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=30)),
                ('onSale', models.BooleanField()),
                ('isSpecial', models.BooleanField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='theme/homer.jpg', upload_to='theme')),
            ],
        ),
    ]
