# Generated by Django 2.1.3 on 2018-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0002_auto_20181116_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='nameID',
            field=models.CharField(default='donut_id', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donut',
            name='image',
            field=models.ImageField(default='theme/homer.jpg', upload_to='theme'),
        ),
    ]
