# Generated by Django 2.1.3 on 2018-11-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0003_auto_20181117_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donut',
            name='id',
        ),
        migrations.AlterField(
            model_name='donut',
            name='nameID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
